name: CI

on:
    push:
        paths:
            - '**/meson.build'
            - '**/meson_options.txt'
            - '**/*.meson'
            - '.github/workflows/*'
            - '**/*.jsonc'
            - '**/*.json'
            - '**/*.xml'
            - '**/*.css'
            - '**/*.c'
            - '**/*.h'

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: alpine:latest

        strategy:
            matrix:
                compiler: [clang, gcc]

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                apk add --no-cache \
                    bash git build-base \
                    clang lld gcc \
                    pkgconf ninja meson \
                    gtk+3.0-dev pipewire-dev \
                    networkmanager-dev glib-dev

            - name: Configure (Meson)
              run: |
                if [ "${{ matrix.compiler }}" = "clang" ]; then
                    CC=clang LD=lld meson setup builddir --buildtype=release
                else
                    CC=gcc meson setup builddir --buildtype=release
                fi

            - name: Build
              run: ninja -C builddir